[bindings.kotlin]
package_name = "com.wire.crypto.uniffi"
cdylib_name = "core_crypto_ffi"

[bindings.swift]
cdylib_name = "core_crypto_ffi"
ffi_module_name = "LibCoreCrypto"
ffi_module_filename = "core_crypto_ffiFFI"
generate_module_map = false


