[bindings.kotlin-native]
package_name = "com.wire.crypto"
cdylib_name = "core_crypto_ffi"

[bindings.kotlin]
package_name = "com.wire.crypto"
cdylib_name = "core_crypto_ffi"

[bindings.swift]
cdylib_name = "core_crypto_ffi"
ffi_module_name = "LibCoreCrypto"
ffi_module_filename = "core_cryptoFFI"
generate_module_map = false
