[bindings.kotlin]
package_name = "com.wire.crypto"
cdylib_name = "core_crypto_ffi"

[bindings.kotlin.custom_types.Timestamp]
imports = [
  "kotlinx.datetime.Instant",
  "kotlinx.datetime.toKotlinInstant",
  "kotlinx.datetime.toJavaInstant",
]
type_name = "Instant"
lift = "{}.toKotlinInstant()"
lower = "{}.toJavaInstant()"

[bindings.swift]
cdylib_name = "core_crypto_ffi"
ffi_module_name = "LibCoreCrypto"
ffi_module_filename = "core_crypto_ffiFFI"
generate_module_map = false

[bindings.typescript]
optOutInterface = true
