use_try_shorthand = true
use_field_init_shorthand = true
max_width = 120
comment_width = 120
wrap_comments = true
newline_style = "Unix"
merge_derives = true
condense_wildcard_suffixes = true
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
