[toolchain]
channel = "nightly-2025-11-06"
components = [
  "rust-analyzer",
  "cargo",
  "rustfmt",
  "clippy",
  "rustc",
  "rust-src",
]
targets = [
  "aarch64-apple-ios",
  "aarch64-apple-ios-sim",
  "aarch64-linux-android",
  "armv7-linux-androideabi",
  "x86_64-linux-android",
  "wasm32-unknown-unknown",
]
