[package]
name = "decode"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-only"

[lints]
workspace = true

[dependencies]
clap = { version = "4.5.37", features = ["derive"] }
proteus-wasm = { workspace = true, features = ["serde"] }
base64 = { workspace = true }
openmls = { workspace = true }
