[package]
name = "wire-e2e-identity"
description = "Public API for Wire end to end identity"
version = "0.8.6"
edition = "2021"
repository = "https://github.com/wireapp/rusty-jwt-tools"
license = "MPL-2.0"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
serde = "1.0"
serde_json = "1.0"
thiserror = "1.0"
rusty-acme = { version = "0.8.6", path = "../acme" }
rusty-jwt-tools = { version = "0.8.6", path = "../jwt" }
jwt-simple = { workspace = true }
derive_more = { version = "0.99", features = ["deref", "from", "into"] }
url = "2.5"
zeroize = "1.7"

uuid = { version = "1.6", optional = true }
rand = { version = "0.8", optional = true }
x509-cert = { version = "0.2", optional = true }
oid-registry = { version = "0.6", optional = true }
time = { version = "0.3", optional = true }

[dependencies.rcgen]
git = "https://github.com/wireapp/rcgen"
tag = "v1.2.2-pre.core-crypto-0.7.0"
version = "=0.9.2"
optional = true

[dev-dependencies]
wire-e2e-identity = { version = "0.8.6", path = ".", features = ["identity-builder"] }
rusty-jwt-tools = { version = "0.8.6", path = "../jwt", features = ["test-utils"] }
rand = "0.8"
base64 = "0.21.0"
url = "2.5"
itertools = "0.12"
uuid = "1.6"
wasm-bindgen-test = "0.3"
hex = "0.4"
webbrowser = "0.8"
rusty-jwt-cli = { version = "0.8.6", path = "../cli" }

openidconnect = "3.0.0-alpha.1"
html_parser = "0.6"
scraper = "0.14"
anyhow = "1.0"
tokio = { version = "1.5", features = ["macros"], default_features = false }
lazy_static = "1.4"
portpicker = "0.1"
pem = "3.0"

[target.'cfg(not(target_family = "wasm"))'.dev-dependencies]
rusty-acme = { version = "0.8.6", path = "../acme" }
reqwest = { version = "0.11", features = ["json", "cookies"], default_features = false }
tokio = { version = "1.5", features = ["macros"], default_features = false }
hyper = { version = "0.14", features = ["server"], default_features = false }
asserhttp = { version = "0.6", features = ["reqwest"] }
testcontainers = "0.15"
oauth2 = "4.3"
http = "0.2"
keycloak = "21"

[target.'cfg(target_family = "wasm")'.dev-dependencies]
rusty-acme = { version = "0.8.6", path = "../acme" }

[features]
default = []
identity-builder = ["dep:rcgen", "dep:rand", "dep:uuid", "dep:x509-cert", "dep:oid-registry", "dep:time"]
