[package]
name = "wire-e2e-identity"
description = "Public API for Wire end to end identity"
version = "0.2.0"
edition = "2021"
repository = "https://github.com/wireapp/rusty-jwt-tools"
license = "MPL-2.0"
publish = false

[dependencies]
serde = "1.0"
serde_json = "1.0"
thiserror = "1.0"
rusty-acme = { version = "0.2", path = "../acme" }
rusty-jwt-tools = { version = "0.2", path = "../jwt" }
jwt-simple = "0.11.3"
derive_more = { version = "0.99", features = ["deref", "from", "into"] }
url = "2.3"

[dev-dependencies]
rand = "0.8"
base64 = "0.21.0"
url = "2.3"
itertools = "0.10"
uuid = "1.2"
wasm-bindgen-test = "0.3"
hex = "0.4"
x509-parser = "=0.14.0"

[target.'cfg(not(target_family = "wasm"))'.dev-dependencies]
rusty-acme = { version = "0.2", path = "../acme", features = ["docker"] }
reqwest = { version = "0.11", features = ["json"], default_features = false }
tokio = { version = "1.5.0", features = ["macros"], default_features = false }
hyper = { version = "0.14", features = ["server"], default_features = false }
asserhttp = { version = "0.5", features = ["reqwest"] }
testcontainers = "0.14"

[target.'cfg(target_family = "wasm")'.dev-dependencies]
rusty-acme = { version = "0.2", path = "../acme" }
