concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}-docs-jvm"
  cancel-in-progress: true

on:
  workflow_call:

env:
  RELEASE: 1

jobs:
  docs-jvm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: set up jdk 17
        uses: actions/setup-java@v5
        with:
          java-version: "17"
          distribution: "adopt"
      - name: gradle setup
        uses: gradle/actions/setup-gradle@v5
      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v5

      - name: download linux library
        uses: ./.github/actions/make/jvm
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}

      - name: download linux bindings
        uses: ./.github/actions/make/bindings-kotlin-jvm
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}

      - name: generate Kotlin docs
        uses: ./.github/actions/make
        with:
          key: docs-kotlin
          make-rule: docs-kotlin
          target-path: target/kotlin/doc/html
          gh-token: ${{ secrets.GITHUB_TOKEN }}

      - name: upload kotlin docs
        uses: actions/upload-artifact@v5.0.0
        with:
          name: kotlin
          path: target/kotlin/doc/html
          retention-days: 1
          overwrite: true
          include-hidden-files: true
          if-no-files-found: error
