name: scheduled


on:
  schedule:
    # runs these jobs on the default branch (main) at 0132 daily UTC (0332 Berlin time)
    - cron: "32 1 * * *"
  workflow_dispatch:
    # runs these jobs when triggered manually

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always
  CARGO_NET_GIT_FETCH_WITH_CLI: true
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

jobs:
  all-features:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-and-cache-rust
      - uses: taiki-e/install-action@nextest
      - run: cargo nextest run --locked --all-features --no-fail-fast --retries 5
        # certain tests are flaky when run in parallel like this, but
        # experiments suggest 5 is enough retries that they'll generally pass eventually
