concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}-test-ts"
  cancel-in-progress: true

on:
  workflow_call:
  workflow_dispatch:

env:
  RELEASE: 1

jobs:
  test-ts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: wireapp/setup-chrome@master
        id: setup-chrome
        with:
          chrome-version: stable
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: download web files
        uses: ./.github/actions/make/web/ts
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
      - name: lint
        run: make ts-check

      - name: test
        uses: ./.github/actions/make
        with:
          key: ts-test
          make-rule: ts-test
          always-run: ${{ github.event_name == 'workflow_dispatch' || github.ref_name == 'main' }}
          gh-token: ${{ secrets.GITHUB_TOKEN }}
